# Generated by Django 3.1.2 on 2020-10-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201004_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='project',
            field=models.CharField(choices=[('1', 'Web Development'), ('2', 'Software Development'), ('3', 'Machine Learning'), ('4', 'Deep Learning'), ('5', 'Natural Language Processing')], max_length=1),
        ),
    ]
